name: 'action-s3cp'
description: 'This action allows you to upload files to a given S3 bucket.'
env:
  AWS_KEY_ID:
    description: 'ID of a programmatic access AWS key attached to an IAM role which has permission to put an object into your target S3 bucket. **Recommend implementing into repository secrets!**'
    required: true
  AWS_KEY_SECRET:
    description: 'Secret of a programmatic access AWS key attached to an IAM role which has permission to put an object into your target S3 bucket. **Recommend implementing into repository secrets!**'
    required: true
  BUCKET:
    description: 'Target bucket for file upload. For upload configuration, see below.'
    required: true
runs:
  using: 'node12'
  pre: 'src/pre.js'
  main: 'src/main.js'
